import './globals.css'
import HeaderComponent from './header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
      <HeaderComponent></HeaderComponent>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
